package pl.lukaszgrymulski;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class EmployeeSearchWindow {
    public JPanel panelMain;
    private JTextField lastNameTextField;
    private JPanel container;
    private JLabel infoLabel;
    private JButton searchButton;
    private JTable resultSetTable;
    private JScrollPane tableArea;
    private JPanel textFieldBg;
    private EmployeeDAO employeeDAO;
    private JFrame frame;

    public void runSearchWindow() {
        JFrame frame = new JFrame("EmployeeSearchWindow");
        frame.setContentPane(new EmployeeSearchWindow().panelMain);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public EmployeeSearchWindow() {
        searchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                try {
                    employeeDAO = new EmployeeDAO();
                    String lastName = lastNameTextField.getText();
                    List<Employee> employees = null;
                    if (lastName != null && lastName.trim().length() > 0) {
                        employees = employeeDAO.searchEmployees(lastName);
                    } else {
                        employees = employeeDAO.getAllEmployees();
                    }
                    EmployeeTableModel model = new EmployeeTableModel(employees);
                    resultSetTable.setModel(model);
                } catch (Exception f) {
                    JOptionPane.showMessageDialog(panelMain, "Couldn't connect to DataBase! Try again later!");
                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("EmployeeSearchWindow example");
        frame.setContentPane(new EmployeeSearchWindow().panelMain);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new BorderLayout(0, 0));
        panelMain.setBackground(new Color(-11974327));
        panelMain.setMaximumSize(new Dimension(500, 400));
        panelMain.setMinimumSize(new Dimension(500, 400));
        panelMain.setOpaque(true);
        panelMain.setPreferredSize(new Dimension(500, 500));
        container = new JPanel();
        container.setLayout(new FlowLayout(FlowLayout.LEFT, 15, 10));
        container.setBackground(new Color(-15724223));
        container.setMaximumSize(new Dimension(500, 500));
        container.setMinimumSize(new Dimension(500, 500));
        container.setOpaque(true);
        container.setPreferredSize(new Dimension(500, 50));
        panelMain.add(container, BorderLayout.NORTH);
        infoLabel = new JLabel();
        infoLabel.setForeground(new Color(-11932118));
        infoLabel.setOpaque(false);
        infoLabel.setText("Enter last name");
        container.add(infoLabel);
        textFieldBg = new JPanel();
        textFieldBg.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        textFieldBg.setBackground(new Color(-15039355));
        container.add(textFieldBg);
        lastNameTextField = new JTextField();
        lastNameTextField.setCaretColor(new Color(-11776948));
        lastNameTextField.setDisabledTextColor(new Color(-15066598));
        lastNameTextField.setForeground(new Color(-658656));
        lastNameTextField.setInheritsPopupMenu(false);
        lastNameTextField.setMargin(new Insets(0, 5, 0, 5));
        lastNameTextField.setMaximumSize(new Dimension(150, 30));
        lastNameTextField.setMinimumSize(new Dimension(150, 30));
        lastNameTextField.setOpaque(false);
        lastNameTextField.setPreferredSize(new Dimension(150, 30));
        lastNameTextField.setSelectedTextColor(new Color(-3728343));
        textFieldBg.add(lastNameTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        searchButton = new JButton();
        searchButton.setBackground(new Color(-15039355));
        searchButton.setBorderPainted(true);
        searchButton.setForeground(new Color(-11932118));
        searchButton.setOpaque(true);
        searchButton.setText("Search");
        container.add(searchButton);
        tableArea = new JScrollPane();
        tableArea.setAutoscrolls(false);
        tableArea.setBackground(new Color(-11974327));
        tableArea.setForeground(new Color(-11974327));
        tableArea.setInheritsPopupMenu(false);
        tableArea.setMaximumSize(new Dimension(500, 500));
        tableArea.setMinimumSize(new Dimension(500, 500));
        tableArea.setOpaque(true);
        tableArea.setPreferredSize(new Dimension(500, 500));
        panelMain.add(tableArea, BorderLayout.WEST);
        resultSetTable = new JTable();
        resultSetTable.setAutoResizeMode(4);
        resultSetTable.setBackground(new Color(-14660472));
        resultSetTable.setForeground(new Color(-12066005));
        resultSetTable.setGridColor(new Color(-16777216));
        resultSetTable.setOpaque(true);
        resultSetTable.setSelectionBackground(new Color(-15066598));
        resultSetTable.setSelectionForeground(new Color(-15841007));
        tableArea.setViewportView(resultSetTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}
